### ISSUE TITLE
Inline CSS

### ISSUE THREAD

**Issue by snowman-repos** [topheman/webpack-babel-starter#4]
Me again :)

I'm trying to update the webpack config to inline the CSS rather than link to an external file. For this I'm using html-webpack-inline-source-plugin:

```
const HtmlWebpackPlugin = require('html-webpack-plugin');
const HtmlWebpackInlineSourcePlugin = require('html-webpack-inline-source-plugin');
.
.
.
plugins.push(new HtmlWebpackPlugin({
  inlineSource: /\.css$/,
.
.
.
plugins.push(new HtmlWebpackInlineSourcePlugin());

```

It works perfectly in development but when I run `build-prod` it still links the external CSS file. Any ideas?

Thanks again!

**Comment by topheman** [comment]
Hi @darryl-snow ,

Sorry, I'm only answering now. If you aven't found out, as specified in the plugin's doc https://www.npmjs.com/package/html-webpack-inline-source-plugin : 

```js
plugins: [
  new HtmlWebpackPlugin({
        inlineSource: '.(js|css)$' // embed all javascript and css inline 
    }),
  new HtmlWebpackInlineSourcePlugin()
] 
```

You'll have to use the `inlineSource` var in the template file `src/index.ejs`.

**Comment by snowman-repos** [comment]
Yep, tried that. It only works in dev though, not production. In index.ejs I have:

```
<link href="<%= webpack.assetsByChunkName['main'][1] %>" rel="stylesheet">
```

Trying `<%= htmlWebpackPlugin.options.inlineSource %>` results in

```
<style>.(js|css)$</style>
```
